platform: linux
image_resource:
  type: docker-image
  source: {repository: registry.mckesson.com/er2niot/java-be, tag: latest}
inputs:
  - name: install-results
outputs:
  - name: cloud-foundry
run:
  path: /bin/bash
  args:
    - -exc
    - |
      cd install-results
      wget http://mirror.cogentco.com/pub/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      tar xvf apache-maven-3.6.3-bin.tar.gz
      export M2_HOME=$(pwd)/apache-maven-3.6.3
      export M2=$M2_HOME/bin
      export PATH=$M2:$PATH
      mvn clean test

