---

resources:
- name: source-code-tests
  type: git
  source:
    uri: https://bitbucket.mckesson.com:8443/scm/~e58sf31/test.git
    branch: master
    username: ((bitbucket-user))
    password: ((bitbucket-pass))

jobs:
- name: build-and-deploy
  public: true
  plan:
  - get: source-code-tests
  - task: install-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: quay.io/cosee-concourse/selenium, tag: latest}
      inputs:
      - name: source-code-tests
      run:
        path: /bin/bash 
        args:
        - -exc
        - |
          apt-get update
          apt-get install -y wget xvfb unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
          apt-get update -y
          apt-get install -y google-chrome-stable
          CHROMEDRIVER_VERSION=78.0.3904.11
          CHROMEDRIVER_DIR=chromedriver
          mkdir $CHROMEDRIVER_DIR
          wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR
          whereis chromedriver
          wget http://mirror.reverse.net/pub/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
          tar xvf apache-maven-3.6.1-bin.tar.gz
          export M2_HOME=$(pwd)/apache-maven-3.6.1
          export M2=$M2_HOME/bin
          export PATH=$M2:$PATH
          cd source-code-tests
          mvn clean install
          
          