---
resources:
  - name: source-code
    type: git
    source:
      uri: https://bitbucket.mckesson.com:8443/scm/~e126cr6/backup_temp.git
      branch: master
      username: ((Henry))
      password: ((Henry-P))
  - name: cloud-foundry
    type: cf
    source:
      api: https://api.sys.dev-west.paas.mckesson.com
      username: ((dev-pcf-user))
      password: ((dev-pcf-pass))
      organization: Pharma-AccessHealth
      space: dev-pp
      skip_cert_check: true

jobs:
  - name: build-and-deploy
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: install
        file: source-code/demo/CI/tasks/install.yml
      - put: cloud-foundry
        params:
          manifest: source-code/demo/CI/manifest/manifest-dev.yml
          path: cloud-foundry
          environment_variables: